/* Generated By:JavaCC: Do not edit this line. CCALParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CCALParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int COMMA = 11;
  /** RegularExpression Id. */
  int SEMICOL = 12;
  /** RegularExpression Id. */
  int COLON = 13;
  /** RegularExpression Id. */
  int EQU = 14;
  /** RegularExpression Id. */
  int LEFT_CURL = 15;
  /** RegularExpression Id. */
  int RIGHT_CURL = 16;
  /** RegularExpression Id. */
  int LEFT_BR = 17;
  /** RegularExpression Id. */
  int RIGHT_BR = 18;
  /** RegularExpression Id. */
  int PLUS_SIGN = 19;
  /** RegularExpression Id. */
  int MINUS_SIGN = 20;
  /** RegularExpression Id. */
  int LOG_NEG = 21;
  /** RegularExpression Id. */
  int LOG_OR = 22;
  /** RegularExpression Id. */
  int LOG_AND = 23;
  /** RegularExpression Id. */
  int IS_EQU = 24;
  /** RegularExpression Id. */
  int NOT_EQU = 25;
  /** RegularExpression Id. */
  int LESS_THAN = 26;
  /** RegularExpression Id. */
  int LESS_EQU = 27;
  /** RegularExpression Id. */
  int GREAT_THAN = 28;
  /** RegularExpression Id. */
  int GREAT_EQU = 29;
  /** RegularExpression Id. */
  int VAR = 30;
  /** RegularExpression Id. */
  int CONST = 31;
  /** RegularExpression Id. */
  int RETURN = 32;
  /** RegularExpression Id. */
  int INT = 33;
  /** RegularExpression Id. */
  int BOOL = 34;
  /** RegularExpression Id. */
  int VOID = 35;
  /** RegularExpression Id. */
  int MAIN = 36;
  /** RegularExpression Id. */
  int IF = 37;
  /** RegularExpression Id. */
  int ELSE = 38;
  /** RegularExpression Id. */
  int TRUE = 39;
  /** RegularExpression Id. */
  int FALSE = 40;
  /** RegularExpression Id. */
  int WHILE = 41;
  /** RegularExpression Id. */
  int SKIPP = 42;
  /** RegularExpression Id. */
  int NUM = 43;
  /** RegularExpression Id. */
  int DIGIT = 44;
  /** RegularExpression Id. */
  int ID = 45;
  /** RegularExpression Id. */
  int CHAR = 46;
  /** RegularExpression Id. */
  int OTHER = 47;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_COMMENT = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<token of kind 6>",
    "\"/*\"",
    "\"/*\"",
    "\"*/\"",
    "<token of kind 10>",
    "\",\"",
    "\";\"",
    "\":\"",
    "\"=\"",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "\"+\"",
    "\"-\"",
    "\"~\"",
    "\"||\"",
    "\"&&\"",
    "\"==\"",
    "\"!=\"",
    "\"<\"",
    "\"<=\"",
    "\">\"",
    "\">=\"",
    "\"var\"",
    "\"const\"",
    "\"return\"",
    "\"integer\"",
    "\"boolean\"",
    "\"void\"",
    "\"main\"",
    "\"if\"",
    "\"else\"",
    "\"true\"",
    "\"false\"",
    "\"while\"",
    "\"skip\"",
    "<NUM>",
    "<DIGIT>",
    "<ID>",
    "<CHAR>",
    "<OTHER>",
  };

}
